### PR TITLE
Added translation to Norwegian Bokmål nb_NO

### PR DESCRIPTION
**Pull request by danibjor**

### CODE REVIEW

**Comment by ammaratef45** [comment]
@danibjor Isn't `no_messages.dart` the right naming way?

**Comment by danibjor** [comment]
We have two variangs of Norwegian. Norwegian Bokmål (the default) `nb_NO`, and Norwegian Nynorsk (hardly anyone uses it) `nn_NO`.

Just `no_messages.dart` is OK for me.

**Comment by ammaratef45** [comment]
@danibjor looks like Japanese isn't the only language who has more than one writing :laughing: 
Thanks for the explanation :+1:

**Comment by andresaraujo** [comment]
Thanks @danibjor you locale is now included in v2.0.11

**Pull request merged**
