### PR TITLE
Fix Arabic wording

### PR DESCRIPTION
**Pull request by salehahmedZ**
I use this amazing package in my production app but I noticed that Arabic wording is not accurate. In Arabic we have different time words for singular, couple and plural(more than one word for plural). so this was my fix .

### CODE REVIEW

**Comment by ammaratef45** [comment]
@salehahmedZ great work :+1:

**Comment by salehahmedZ** [comment]
@ammaratef45 Glad you liked it.

**Comment by andresaraujo** [comment]
thanks @ammaratef45 @salehahmedZ will release a new version today with this fix

**Comment by andresaraujo** [comment]
@salehahmedZ your changes are now in v2.0.15, thanks

**Pull request merged**
