### PR TITLE
update intl 0.18.0

### PR DESCRIPTION
**Pull request by nguyenxdat**

### CODE REVIEW

**Review by iChicago — APPROVED** [review]

**Comment by iChicago** [comment]
> @iChicago .....
> 
> Can we have this fix deployed soon...
> 
> Really counting hours on this..
> 
> 
> 
> Kind Regards.

I wish that but I'm not the owner of this package and I don't have any authority to merge.

**Comment by simplenotezy** [comment]
https://github.com/andresaraujo/timeago.dart/pull/206

**Comment by andresaraujo** [comment]
This is now fixed in v3.4.0. Sorry for the delay

**Comment by Coder-Manuel** [comment]
Great..
Thanks @andresaraujo .....

**Pull request merged**
